name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push, or for pull requests against master
  push:
    paths-ignore:
      - NEWS
  pull_request:
    branches: [ master ]
    paths-ignore:
      - NEWS

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  linux:
    runs-on: 'ubuntu-20.04'
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Install CCache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: linux
    - name: Install package dependencies
      run: |
        sudo apt-get update
        sudo apt-get install \
            gettext \
            libwxgtk3.0-gtk3-dev \
            libavcodec-dev \
            libavformat-dev \
            libproj-dev \
            libswscale-dev \
            mesa-common-dev \
            libglu1-mesa-dev \
            libx11-dev \
            libxext-dev \
            ghostscript \
            netpbm \
            x11proto-core-dev \
            liblocale-po-perl \
            unifont \
            docbook-utils \
            w3m
    - name: bootstrap source tree
      run: autoreconf -fiv
    - name: configure
      run: ./configure CC='ccache gcc' CXX='ccache g++'
    - name: make
      run: make -j2
    - name: Run tests
      run: make check VERBOSE=1
    - name: Check generated files are in .gitignore
      # grep '^' passes through all input while giving a non-zero exit status
      # if that input is empty.
      run: |
        printf '%s\n' .ccache > ".git/info/exclude"
        git status --porcelain|grep '^' && { echo "The generated files listed above are not in .gitignore" ; exit 1; }; true

  valgrind:
    runs-on: 'ubuntu-20.04'
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Install CCache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: valgrind
    - name: Install package dependencies
      run: |
        sudo apt-get update
        sudo apt-get install \
            gettext \
            libwxgtk3.0-gtk3-dev \
            libavcodec-dev \
            libavformat-dev \
            libproj-dev \
            libswscale-dev \
            mesa-common-dev \
            libglu1-mesa-dev \
            libx11-dev \
            libxext-dev \
            ghostscript \
            netpbm \
            x11proto-core-dev \
            liblocale-po-perl \
            unifont \
            docbook-utils \
            w3m
        sudo apt-get install valgrind
    - name: bootstrap source tree
      run: autoreconf -fiv
    - name: configure
      run: ./configure CC='ccache gcc' CXX='ccache g++'
    - name: make
      run: make -j2
    - name: Run tests
      run: VALGRIND=valgrind make check VERBOSE=1
    - name: Check generated files are in .gitignore
      # grep '^' passes through all input while giving a non-zero exit status
      # if that input is empty.
      run: |
        printf '%s\n' .ccache > ".git/info/exclude"
        git status --porcelain|grep '^' && { echo "The generated files listed above are not in .gitignore" ; exit 1; }; true

  macos:
    runs-on: 'macos-latest'
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Install CCache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: macos
    - name: Install package dependencies
      run: |
        brew update
        brew install \
            automake \
            ffmpeg \
            gettext \
            gnu-tar \
            netpbm \
            proj \
            wxwidgets
        brew link --force gettext
        sudo cpan -T -i local::lib < /dev/null
        sudo cpan -I -T -i Locale::PO < /dev/null
    - name: bootstrap source tree
      run: |
        autoreconf -fiv
        V=`sed -e 's/^AC_INIT[^,]*, *\[\([^]]*\)\].*/\1/p;d' configure.ac` ; curl https://survex.com/software/$V/survex-$V.tar.gz | gtar --strip-components=1 --skip-old-files -zxf - ; ls -lrt lib ; touch lib/unifont.pixelfont lib/preload_font.h; echo ; ls -lrt doc; touch doc/*.1 doc/manual.txt doc/manual.pdf doc/manual/stampfile
    - name: configure
      run: ./configure CC='ccache gcc' CXX='ccache g++'
    - name: make
      run: |
        eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"
        make -j3
    - name: Run tests
      run: make -Ctests check VERBOSE=1
    - name: Check generated files are in .gitignore
      # grep '^' passes through all input while giving a non-zero exit status
      # if that input is empty.
      run: |
        #find . \( -name 'config.guess~' -o -name 'config.sub~' -o -name 'install-sh~' \) -delete
        printf '%s\n' .ccache > ".git/info/exclude"
        git status --porcelain|grep '^' && { echo "The generated files listed above are not in .gitignore" ; exit 1; }; true

  macos10-15:
    runs-on: 'macos-10.15'
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Install CCache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: macos10-15
    - name: Install package dependencies
      run: |
        brew update
        brew install \
            automake \
            ffmpeg \
            gettext \
            gnu-tar \
            netpbm \
            proj \
            wxwidgets
        brew link --force gettext
        sudo cpan -T -i local::lib < /dev/null
        sudo cpan -I -T -i Locale::PO < /dev/null
    - name: bootstrap source tree
      run: |
        autoreconf -fiv
        V=`sed -e 's/^AC_INIT[^,]*, *\[\([^]]*\)\].*/\1/p;d' configure.ac` ; curl https://survex.com/software/$V/survex-$V.tar.gz | gtar --strip-components=1 --skip-old-files -zxf - ; ls -lrt lib ; touch lib/unifont.pixelfont lib/preload_font.h; echo ; ls -lrt doc; touch doc/*.1 doc/manual.txt doc/manual.pdf doc/manual/stampfile
    - name: configure
      run: ./configure CC='ccache gcc' CXX='ccache g++'
    - name: make
      run: |
        eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"
        make -j3
    - name: Run tests
      run: make -Ctests check VERBOSE=1
    - name: Check generated files are in .gitignore
      # grep '^' passes through all input while giving a non-zero exit status
      # if that input is empty.
      run: |
        #find . \( -name 'config.guess~' -o -name 'config.sub~' -o -name 'install-sh~' \) -delete
        printf '%s\n' .ccache > ".git/info/exclude"
        git status --porcelain|grep '^' && { echo "The generated files listed above are not in .gitignore" ; exit 1; }; true
